# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: gha-demo-dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./gha.demo/gha.demo.csproj
    - name: Build
      run: dotnet build ./gha.demo/gha.demo.csproj --configuration Release --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
