# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: gha-demo-dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Print Directory List 
      run: ls -la
    - name: Restore dependencies
      run: dotnet restore ./gha.demo/gha.demo/gha.demo.csproj
    - name: Build
      run: dotnet build ./gha.demo/gha.demo/gha.demo.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./gha.demo/gha.demo.tests/gha.demo.tests.csproj --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./gha.demo/gha.demo/gha.demo.csproj --configuration Release  --no-build --output ./publish
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name gha-demo --version-label gha-demo --source-bundle S3Bucket=elasticbeanstalk-ap-southeast-2-435849147344,S3Key=publish.zip
        aws elasticbeanstalk update-environment --application-name gha-demo --environment-name Gha-demo-env --version-label gha-demo
