name: learn-github-actions
run-name: ${{github.actor}} is learning github actions
on: [push]
jobs:
  checks-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/
        name: action demo

      - uses: actions/checkout@v1
      - name: Test variables      
        run: ./.github/client.ps1
        shell: pwsh
        env:
            logfilename: example.log
            errorFilename: error.log
        

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - run: npm install -g bats
      # - run: bats -v
